# Generated by Django 3.0.5 on 2020-07-14 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('thumbnail', models.FileField(upload_to='thumbnail/', verbose_name='Главное фото')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('site', models.SlugField(blank=True, null=True, verbose_name='Сайт')),
                ('mail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Эл.почта')),
                ('inst', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инстаграмм')),
                ('fb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Феисбук')),
                ('vk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вконтакте')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=19, verbose_name='Ширина')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=19, verbose_name='Долгота')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Eat', to='rubrics.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Где покушать',
                'verbose_name_plural': 'Где покушать',
            },
        ),
        migrations.CreateModel(
            name='Go',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('thumbnail', models.FileField(upload_to='thumbnail/', verbose_name='Главное фото')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Go', to='rubrics.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Куда сходить',
                'verbose_name_plural': 'Куда сходить',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('stars', models.IntegerField(blank=True, null=True, verbose_name='Количество звезд')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('thumbnail', models.FileField(upload_to='thumbnail/', verbose_name='Главное фото')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('site', models.SlugField(blank=True, null=True, verbose_name='Сайт')),
                ('mail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Эл.почта')),
                ('inst', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инстаграмм')),
                ('fb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Феисбук')),
                ('vk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вконтакте')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=19, verbose_name='Ширина')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=19, verbose_name='Долгота')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активно')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stay', to='rubrics.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Где остановиться',
                'verbose_name_plural': 'Где остановиться',
            },
        ),
        migrations.CreateModel(
            name='TypesEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип (Где покушать)',
                'verbose_name_plural': 'Типы (Где покушать)',
            },
        ),
        migrations.CreateModel(
            name='TypesGo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип (Куда сходить)',
                'verbose_name_plural': 'Типы (Куда сходить)',
            },
        ),
        migrations.CreateModel(
            name='TypesStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип (Где остановиться)',
                'verbose_name_plural': 'Типы (Где остановиться)',
            },
        ),
        migrations.CreateModel(
            name='StayPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='gallery/<django.db.models.fields.related.ForeignKey>', verbose_name='Фотографии')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='rubrics.Stay', verbose_name='Рубрика')),
            ],
        ),
        migrations.AddField(
            model_name='stay',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stay', to='rubrics.TypesStay', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='ReviewsStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rubrics.Stay', verbose_name='Rubric')),
            ],
            options={
                'verbose_name': 'Отзыв(Где остановиться)',
                'verbose_name_plural': 'Отзывы(Где остановиться)',
            },
        ),
        migrations.CreateModel(
            name='ReviewsEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rubrics.Eat', verbose_name='Rubric')),
            ],
            options={
                'verbose_name': 'Отзыв(Где поесть)',
                'verbose_name_plural': 'Отзывы(Где поесть)',
            },
        ),
        migrations.CreateModel(
            name='GoPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='gallery/<django.db.models.fields.related.ForeignKey>', verbose_name='Фотографии')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='rubrics.Go', verbose_name='Рубрика')),
            ],
        ),
        migrations.AddField(
            model_name='go',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Go', to='rubrics.TypesGo', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='EatPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='gallery/<django.db.models.fields.related.ForeignKey>', verbose_name='Фотографии')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='rubrics.Eat', verbose_name='Рубрика')),
            ],
        ),
        migrations.AddField(
            model_name='eat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eat', to='rubrics.TypesEat', verbose_name='Тип'),
        ),
    ]
