# Generated by Django 3.0.5 on 2020-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail_news/', verbose_name='Главное фото'),
        ),
    ]
