# Generated by Django 3.0.5 on 2020-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cities',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cities',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='eat',
            name='address_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='eat',
            name='address_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='eat',
            name='address_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='eat',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='eat',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='eat',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='eat',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='eat',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='eat',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='go',
            name='address_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='go',
            name='address_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='go',
            name='address_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='go',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='go',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='go',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='go',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='go',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='go',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stay',
            name='address_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='stay',
            name='address_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='stay',
            name='address_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='stay',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='stay',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='stay',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='stay',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stay',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stay',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typeseat',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typeseat',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typeseat',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typesgo',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typesgo',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typesgo',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typesstay',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typesstay',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typesstay',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
