# Generated by Django 3.0.5 on 2020-07-18 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0005_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akmola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=' Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name=' Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name=' Заголовок')),
                ('title_kk', models.CharField(max_length=100, null=True, verbose_name=' Заголовок')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail_akmola', verbose_name='Главное фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('content_en', models.TextField(null=True, verbose_name='Контент')),
                ('content_kk', models.TextField(null=True, verbose_name='Контент')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Об области',
                'verbose_name_plural': 'Об области',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
