# Generated by Django 3.0.5 on 2020-07-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0007_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
