# Generated by Django 3.0.5 on 2020-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0009_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='events',
            name='address_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='events',
            name='address_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='events',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='events',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='events',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='events',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='events',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='events',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
