# Generated by Django 3.0.5 on 2020-07-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0013_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail_tours', verbose_name='Главное фото'),
        ),
    ]
