# Generated by Django 3.0.5 on 2020-07-27 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0015_auto_20200720_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail_tours', verbose_name='Главное фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Туристу',
                'verbose_name_plural': 'Туристу',
            },
        ),
        migrations.AlterField(
            model_name='eatphotos',
            name='images',
            field=models.FileField(upload_to='gallery', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='gophotos',
            name='images',
            field=models.FileField(upload_to='gallery', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='stayphoto',
            name='images',
            field=models.FileField(upload_to='gallery', verbose_name='Фотографии'),
        ),
    ]
