# Generated by Django 3.0.5 on 2020-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0019_auto_20200728_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpages',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='staticpages',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail_static_pages', verbose_name='Главное фото'),
        ),
    ]
