# Generated by Django 3.0.5 on 2020-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0020_auto_20200728_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpages',
            name='type',
            field=models.CharField(blank=True, choices=[('where_to_stay', 'Где остановиться'), ('where_to_eat', 'Где поесть')], max_length=30, null=True, verbose_name='Тип'),
        ),
    ]
