# Generated by Django 3.0.5 on 2020-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0021_auto_20200728_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Описание')),
                ('images', models.FileField(blank=True, null=True, upload_to='gallereia', verbose_name='Галлерея фото')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлерея',
            },
        ),
    ]
