# Generated by Django 3.0.5 on 2020-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0024_auto_20200729_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='number',
            field=models.IntegerField(default=0, verbose_name='id'),
        ),
    ]
