# Generated by Django 3.0.5 on 2020-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0025_gallery_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='isTop',
            field=models.BooleanField(default=False, verbose_name='Топ'),
        ),
    ]
