# Generated by Django 3.0.5 on 2020-08-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0026_stay_istop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail_tops', verbose_name='Главное фото')),
                ('slug', models.SlugField(unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tops', to='rubrics.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Сайдбар(где поесть)',
                'verbose_name_plural': 'Сайдбар(где поесть)',
            },
        ),
    ]
