# Generated by Django 3.0.5 on 2020-08-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0028_auto_20200802_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebartostay',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sidebartostay',
            name='title_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sidebartostay',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
