# Generated by Django 3.0.5 on 2020-08-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0029_auto_20200802_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourists',
            options={'verbose_name': 'Туристу', 'verbose_name_plural': ' Туристу'},
        ),
    ]
