# Generated by Django 3.0.5 on 2020-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0030_auto_20200804_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourists',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='tours',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
