# Generated by Django 3.0.5 on 2020-08-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0032_auto_20200804_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='')),
                ('title_kk', models.CharField(max_length=50, null=True, verbose_name='')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail_national_foods', verbose_name='Главное фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('content_en', models.TextField(null=True, verbose_name='Контент')),
                ('content_kk', models.TextField(null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Национальное блюдо',
                'verbose_name_plural': 'Национальные блюда',
            },
        ),
    ]
